### ISSUE TITLE
EffectCallback in a zero duration animation is called twice.

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#286]
See [the demo](http://jsbin.com/curopogaxa/2/edit?html,js,output).

Clicking the "Run with JS" button in the result panel should reveal the problem.

From https://lists.w3.org/Archives/Public/public-fx/2015JanMar/0040.html

**Comment by shans** [comment]
Unless I understand, this isn't an error.

(1) effect callbacks call once per changed tf value
(2) non-filling animations have a tf value of 1

So the expected behavior of that code is that the callback is called once, right at the beginning of the sequence, with a tf of null.

I think you want something like this instead:
var d1 = document.getElementById("d1");
var d2 = document.getElementById("d2");
var anim = new AnimationSequence([
  new Animation(d1, [
    {transform: 'translateX(0)'},
    {transform: 'translateX(100px)'},
  ], 2000),
  new Animation(null, function (tf) {
    if (tf == 1)
      d1.classList.add("moved");
  }, {fill: 'forwards'}),
  new Animation(d2, [
    {transform: 'translateX(0)'},
    {transform: 'translateX(100px)'},
  ], 2000)
]);
document.timeline.play(anim);

**Comment by hgl** [comment]
Oh, thank you. Looks like I didn't understand time fraction very well, should reread spec again.

Also I thought since I modified the DOM directly in the EffectCallback, and it's going to stick, so forwards fill mode is unnecessary. Didn't know web-animations is able to reverse it.
