### ISSUE TITLE
display property not overridden by animation in native impl

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#394]
http://jsbin.com/vekakezuwa/1/edit?html,css,js,output

There is supposed be a teal box displayed, but in chrome, nothing is displayed.

This doesn't relate to the polyfill, but I guess you guys also write the native impl? Guess I will just report it here. Let me know if I should move this to crbugs.

**Comment by Martin-Pitt** [comment]
Display blocks are 'not animatable' in CSS animations either, due to spec.
If the polyfill doesn't do it then this should be working as intended.

I know it sucks, because I think display should be perfectly reasonably animatable when given a step easing/timing function with only two states.

**Comment by hgl** [comment]
According to the spec, it should be animatable, I believe this is a chrome bug.

Hope the native impl could catch up soon. In the mean while, I'd like to suggest that the guarding code should test for properties like `display`, and when browsers can't animate them, let the polyfill kick in.

Thoughts?

**Comment by shans** [comment]
It's not clear that this should be animatable.

Setting display can change running animations (animations are cancelled inside display: none subtrees). This makes display somewhat like the animation-* and transition-* properties, which are not animatable because of the fact that changing them can impact the state of running animations.

**Comment by hgl** [comment]
I posted the previous message when we haven't chatted on irc. :)

So have you reached a consensus with Birtles on this topic?
